### ISSUE TITLE
`peerDependency` points to a non-existent version -> no way to install on npm 3

### ISSUE THREAD

**Issue by bebraw** [jaketrent/html-webpack-template#1]
Your package has set

``` json
  "peerDependencies": {
    "html-webpack-plugin": "2.x"
  }
```

The problem is that [html-webpack-plugin](https://www.npmjs.com/package/html-webpack-plugin) doesn't have a 2.x version available yet. This causes the installation of html-webpack-template to fail on npm 3.

**Comment by jaketrent** [comment]
@bebraw Thanks for the notice.  

I have pushed two dist-tags to npm:

{ latest: '2.5.2', beta: '3.0.2' }

Default installs now go to latest.  To try out the beta, 

`npm install html-webpack-template@3`

Thanks for your help.

**Comment by bebraw** [comment]
@jaketrent Ok, cool. I brought this up as it had potential to break things for guys going through http://survivejs.com/webpack_react/webpack_and_react/ . :+1:

Thanks for the fast fix!

**Comment by jaketrent** [comment]
@bebraw Sweet tutorial!  That looks really nice.  Happy to be a part of it.  Sorry for any disruption.
