### ISSUE TITLE
Integrate external manifest file

### ISSUE THREAD

**Issue by tusharmath** [jaketrent/html-webpack-template#14]
How do the example load `manifest` file?

https://github.com/jaketrent/html-webpack-template/blob/master/index.ejs#L2

**Comment by jaketrent** [comment]
@tusharmath That's a good question.  I believe that's just an artifact from the template I based this off of.  I can't remember which one that is.  I usually just glance over those lines and haven't even documented it.  If you figure it out, let's add it to the docs.

**Comment by bebraw** [comment]
You could try pushing this issue upstream or using `git blame` against the original template at html-webpack-plugin. That alone might explain it.

**Comment by jaketrent** [comment]
I don't have a ton of context on this, and it's not moving.  Closing for now.  Reopen if you have suggestions/code for how to proceed.  Thanks!
