### ISSUE TITLE
Any way to use html-webpack-template to generate Static Site?

### ISSUE THREAD

**Issue by michael-iglesias** [jaketrent/html-webpack-template#15]
Hey Jake,

I was wondering if there was any way to use html-webpack-template to prerender my index.html page. I've come across other Webpack plugins like 'static-jsx-webpack-plugin', 'static-site-generator-webpack-plugin', and others which I'd like to use alongside this plugin.

Any suggestions on how to proceed?

Thanks,
Michael

**Comment by jaketrent** [comment]
I haven't done it, but my guess is that you could.  It's all node, right?  So, if you put it behind a server endpt, you should be able to code something custom up.  I don't know of something prepackaged.  Good luck!
