### ISSUE TITLE
Initial application state

### ISSUE THREAD

**Issue by andrewmclagan** [jaketrent/html-webpack-template#18]
Any suggestions on how to inject initial state for a javascript application?

Initial state would be unique for each visitor, so after webpack compilation has already run and the html file is built?

**Comment by ifokeev** [comment]
I use `https://github.com/cheeriojs/cheerio` for it.
But I would like to share index.ejs between node-server and react-client, but the plugin compiles it to html =\

**Comment by jaketrent** [comment]
Hey @andrewmclagan .  In my experience, the server can bootstrap the client app with either js data written to the served index.html or the client can make an API request back to the server on app load.  

In the case of the first option, html-webpack-template can support this via the `window` config attribute.  See the "Basic usage" example in the readme, where `window.env` is utilized https://github.com/jaketrent/html-webpack-template#basic-usage .
