### ISSUE TITLE
Do you still maintain this repo?

### ISSUE THREAD

**Issue by hejiaji** [jaketrent/html-webpack-template#19]
Firstly thanks for create this convenient package that is make html template easier for us.

But recently I have a requirement that needs to customize the meta tags for disabling "user-scalable" , but right now the repo doesn't support this function and apparently i don't want to add a custom template to my project.

I saw one pull request that from  @renjithgr which perfectly solves the problem, why don't you merge it? i thought it would be useful and helpful. And could you tell me why if you don't want to merge it?

**Comment by renjithgr** [comment]
We are using this template in production. Since my pull request is still pending, we are using a copy of this template.

**Comment by jaketrent** [comment]
Hey @hejiaji and @renjithgr, how are you?  I didn't realize that these PRs were pending.  I obviously need to adjust notifications from this repo.  I'll take a look..., thanks.

**Comment by renjithgr** [comment]
Now I can update my project deps. Thanks!

**Comment by hejiaji** [comment]
@renjithgr Do you work in ThoughtWorks?   This is a ThoughtWorker from Beijing office

**Comment by hejiaji** [comment]
@jaketrent Thanks dude!

**Comment by renjithgr** [comment]
@hejiaji Yes I do. I am from Bangalore office.
