### ISSUE TITLE
Support for base element

### ISSUE THREAD

**Issue by MarkLunney** [jaketrent/html-webpack-template#2]
I already posted this in [html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin/issues/181#issuecomment-172857303), they suggested it would be a better fit for this template, which I'm inclined to agree with.

Currently my only reason for customizing the default template is to set a [base URL](https://developer.mozilla.org/en/docs/Web/HTML/Element/base), which is required when using [react-router](https://github.com/rackt/history/blob/master/docs/BasenameSupport.md) on a sub-directory.

As it is common to use a different base URL for development and deployment, it would be useful to be able to specify this as a config option.

**Comment by jaketrent** [comment]
Added `baseHref` option as of v3.1.5
