### ISSUE TITLE
Template execution failed

### ISSUE THREAD

**Issue by warrenronsiek** [jaketrent/html-webpack-template#20]
Hi, after upgrading to 5.1.0 I am getting the following error when I try to build with webpack:

> ERROR in Template execution failed: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
> ERROR in   TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
> - index.ejs:150 
>   [react-hot-boilerplate]/[html-webpack-template]/index.ejs:150:45
> - index.ejs:183 module.exports
>   [react-hot-boilerplate]/[html-webpack-template]/index.ejs:183:4
> - index.js:255 
>   [react-hot-boilerplate]/[html-webpack-plugin]/index.js:255:16
> - util.js:16 tryCatcher
>   [react-hot-boilerplate]/[html-webpack-plugin]/[bluebird]/js/release/util.js:16:23
> - promise.js:504 Promise._settlePromiseFromHandler
>   [react-hot-boilerplate]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:504:31
> - promise.js:561 Promise._settlePromise
>   [react-hot-boilerplate]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:561:18
> - promise.js:598 Promise._settlePromiseCtx
>   [react-hot-boilerplate]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:598:10
> - async.js:143 Async._drainQueue
>   [react-hot-boilerplate]/[html-webpack-plugin]/[bluebird]/js/release/async.js:143:12
> - async.js:148 Async._drainQueues
>   [react-hot-boilerplate]/[html-webpack-plugin]/[bluebird]/js/release/async.js:148:10
> - async.js:17 Immediate.Async.drainQueues
>   [react-hot-boilerplate]/[html-webpack-plugin]/[bluebird]/js/release/async.js:17:14

Downgrading to 5.0 solved the problem.

**Comment by thethreeonee** [comment]
Same here

**Comment by bebraw** [comment]
Same, https://github.com/survivejs/react-boilerplate/issues/5 .
