### ISSUE TITLE
Option to set another types of apps (AngularJS, Angular2...)

### ISSUE THREAD

**Issue by michaeljota** [jaketrent/html-webpack-template#34]
Hi! Thanks you for this project. I wonder if you can set an option to define another types of webapps.
- AngularJS uses a custom html attribute to define the root of the application.
- Angular2 uses a custom html tag to define the main view of the application, cause the actual bootstrap it's done in compilation. 

I guess other frameworks would use a different way to do this.

**Comment by jwickens** [comment]
For angular 1 you bootstrap manually:

``` js
Angular.bootstrap(document.getElementById('app'), ['app']);
```

**Comment by jaketrent** [comment]
No movement here for a couple months.  Closing for now...

**Comment by michaeljota** [comment]
Do you mind if I send a PR?

**Comment by jaketrent** [comment]
I don't mind at all.
