### ISSUE TITLE
npm install instructions for version 3 are wrong

### ISSUE THREAD

**Issue by leojh** [jaketrent/html-webpack-template#4]
In the npm page for this library, it states the following: 
##### Beta version

For the new version that works with html-webpack-plugin@2.x, npm install html-webpack-plugin@3.

...

it should read " ... ... npm install html-webpack-template@3."

Notice that the name of the npm package is wrong

**Comment by bebraw** [comment]
v3 is the default now. This is likely safely to close.

**Comment by jaketrent** [comment]
Yes, now instead of referencing beta, the README references legacy if you still need those versions.  Closing.
