### ISSUE TITLE
Outdated Optional Tags

### ISSUE THREAD

**Issue by PaulSearcy** [jaketrent/html-webpack-template#47]
Would it be possible to remove the 'conditional IE tags' ( etc..) and `<meta http-equiv="X-UA-Compatible" content="IE=edge">` from the default index.ejs file?

Heres a great SO question and answers on the meta tag part. https://stackoverflow.com/questions/26346917/why-use-x-ua-compatible-ie-edge-anymore

**Comment by jaketrent** [comment]
Removed in 5.6.0.  Thanks for your interest.
