### ISSUE TITLE
FYI: Not compatible with HtmlWebpackInlineChunkPlugin

### ISSUE THREAD

**Issue by dylan-kerr** [jaketrent/html-webpack-template#48]
I've been attempting to use https://www.npmjs.com/package/html-webpack-inline-chunk-plugin to inline the webpack runtime, and was finding that the changes made by that plugin were not being persisted into the generated HTML.

Some debugging identified that the modification of script tags during the `html-webpack-plugin-alter-asset-tags` event is only relevant when using HtmlWebpackPlugin's native script tag injection, which is necessarily disabled for the use of this template.

I'm not blaming anyone or suggesting a change, I just wanted to document this publicly to maybe save some future head-scratching. The workaround is to use https://www.npmjs.com/package/inline-manifest-webpack-plugin as suggested by this template's README.

**Comment by jaketrent** [comment]
Closing as a nice hint for future devs working on similar things.  Thanks for the hint.
