### ISSUE TITLE
Support Google Tag Manager 

### ISSUE THREAD

**Issue by jamesdh** [jaketrent/html-webpack-template#52]
Currently the template supports adding a Google Analytics script. Google Tag Manager on the other hand can do much more, and can be used to install Google Analytics as well (among other things). So basically by supporting GTM, you get a more general purpose tool that does GA and more.

**Comment by jaketrent** [comment]
GTM and other html can now be injected as snippets since https://github.com/jaketrent/html-webpack-template/pull/62
