### ISSUE TITLE
html-webpack-template not generating html

### ISSUE THREAD

**Issue by raymondoh** [jaketrent/html-webpack-template#56]
Hi. After trying the html-webpack-plugin, I have decided to try the template plugin. There are no errors when I run my production build, all of my scripts and title tags are generated. But absolutely no html shows up on the page i.e. no html content whatsoever. The only things on my index page are the background image and background color. My template options include inject: true and template: require('html-webpack-template'). Any ideas what could be wrong. Thanks.

**Comment by jaketrent** [comment]
Hey @raymondoh.  I'm not sure what exactly is going on, but I'd encourage you to change to use the required parameters to the template:

https://github.com/jaketrent/html-webpack-template#basic-usage

ie, `inject: false`

Hopefully that helps.  Good luck!

**Comment by jaketrent** [comment]
I'm going to assume this has been resolved by now.  If not, feel free to ping again.
