### ISSUE TITLE
NPM packages include .idea directory

### ISSUE THREAD

**Issue by edmorley** [jaketrent/html-webpack-template#58]
Hi!

Some of the published packages include an `.idea/` directory, eg:
```
$ curl -sSfL https://registry.npmjs.org/html-webpack-template/-/html-webpack-template-5.5.1.tgz  | tar -zt | grep '.idea'
package/.idea/.name
package/.idea/html-webpack-template.iml
package/.idea/jsLibraryMappings.xml
package/.idea/libraries/html_webpack_template_node_modules.xml
package/.idea/misc.xml
package/.idea/modules.xml
package/.idea/vcs.xml
package/.idea/workspace.xml
```

I think it would make sense to add this directory to `.npmignore`.

**Comment by edmorley** [comment]
Actually it looks like there isn't an existing `.npmignore` and that the `.gitignore` is being used as a fallback. As such, just adding the `.idea` directory to `.gitignore` should be sufficient :-)

**Comment by jaketrent** [comment]
Thanks for seeing this.  Added .npmignore with .idea in it.
