### ISSUE TITLE
The 6.0.1 release contains older content than the 5.6.0 release

### ISSUE THREAD

**Issue by edmorley** [jaketrent/html-webpack-template#59]
Hi!

In mozilla-neutrino/neutrino-dev#184 we were trying to work out why we couldn't use the language customisation feature from 49ea502da1c4e805cadbf12e745ce982332cc06d, even though we thought we were using the latest version of this plugin (6.0.1).

It turns out that the most recent (in terms of date) release of this plugin was given the version 5.6.0, which is a lower number than the two releases prior to it (which were 6.0.0 and 6.0.1). This means people using `^6.0.1` as a version range are not actually getting the most recent version of the plugin. (See the NPM versions/dates below)

Please could a new release be published with version 6.0.2 or higher, so the recent fixes are picked up?

```
$ npm view html-webpack-template time

{ modified: '2017-09-14T10:02:15.479Z',
  created: '2014-12-26T15:08:05.270Z',
  ...
  '5.5.1': '2016-12-19T22:19:07.863Z',
  '6.0.0': '2016-12-21T23:48:11.283Z',
  '6.0.1': '2017-01-27T22:48:26.960Z',
  '5.6.0': '2017-07-11T12:40:09.969Z' }
```

**Comment by jaketrent** [comment]
Version v6.0.2 published at has dist-tag of "latest".  Should be good to roll now.
