### ISSUE TITLE
Add git tags for recent releases

### ISSUE THREAD

**Issue by edmorley** [jaketrent/html-webpack-template#60]
Hi!

When trying to figure out #59, I noticed that the most recent git tag was for 5.2.0, which made debugging that issue harder.

Please could the following tags be added? 
* 5.3.0 -> aad4ea769a5f503e223bca861eb6e502ae63083d
* 5.4.1 -> 3f7144b37682db763b52213849f50d51bde6a2c1
* 5.4.2 -> 6600b684551f6d27eefabc42fe711c6317605187
* 5.5.0 -> edc8e1ffa4ca5aa78154fe159a249a24b2423c65
* 5.5.1 -> 3466e4a88b78c514a46c7dc399541f1c60a88fa9
* 6.0.0 -> 3ad9fdd8ccbfcef262f5dbe69d69f973eb858709 
* 6.0.1 -> 739fb356bcc7b02ba89950471283c21210d57741
* 5.6.0 -> e9043e2147c92cae7b985609545391529f689e20 (this release is actually "newer" than 6.0.1)

(This list was generated using a combination of the NPM `gitHead` value, with confirmation by diffing a local checkout of the repo against the NPM tarball).

Many thanks :-)

**Comment by jaketrent** [comment]
@edmorley thanks for compiling this.  Yes, I will publish these tags this week.  Thank you!

**Comment by jaketrent** [comment]
Ran:
```
$ git tag -a v5.3.0 aad4ea7
$ git tag -a v5.4.1 3f7144b
$ git tag -a v5.4.2 6600b68
$ git tag -a v5.5.0 edc8e1f
$ git tag -a v5.5.1 3466e4a
$ git tag -a v6.0.0 3ad9fdd
$ git tag -a v6.0.1 739fb35

$ git tag -a v5.6.0 e9043e2
fatal: tag 'v5.6.0' already exists

$ git push --tags origin master
Counting objects: 16, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (16/16), done.
Writing objects: 100% (16/16), 1.83 KiB | 938.00 KiB/s, done.
Total 16 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5), completed with 3 local objects.
To github.com:jaketrent/html-webpack-template.git
   19f5454..e65a4ec  master -> master
 * [new tag]         v5.3.0 -> v5.3.0
 * [new tag]         v5.4.1 -> v5.4.1
 * [new tag]         v5.4.2 -> v5.4.2
 * [new tag]         v5.5.0 -> v5.5.0
 * [new tag]         v5.5.1 -> v5.5.1
 * [new tag]         v5.6.0 -> v5.6.0
 * [new tag]         v6.0.0 -> v6.0.0
 * [new tag]         v6.0.1 -> v6.0.1
 * [new tag]         v6.0.2 -> v6.0.2
```

Working for your purposes on your end?

**Comment by edmorley** [comment]
Looks great now! Thank you for this and the other fixes :-)
