### ISSUE TITLE
Tag missing for 6.1.0 release

### ISSUE THREAD

**Issue by edmorley** [jaketrent/html-webpack-template#64]
Hi!

Looking at the repository I thought 6.0.2 was the last release, since that's the most recent Git tag present, however NPM is reporting 6.1.0 as the latest?
https://www.npmjs.com/package/html-webpack-template

Many thanks :-)

**Comment by jaketrent** [comment]
6.1.0 tag pushed.  @edmorley Do you see it now?

**Comment by edmorley** [comment]
Yeah - https://github.com/jaketrent/html-webpack-template/releases/tag/v6.1.0

Many thanks :-)
