### ISSUE TITLE
bodyHtmlSnippet not working for me

### ISSUE THREAD

**Issue by JESii** [jaketrent/html-webpack-template#67]
I have the following definition in my webpack config:
```javascript
      new HtmlWebpackPlugin({
        inject: false,
        template: require('html-webpack-template'),
        links: [
         {rel: "stylesheet", 
           href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", 
          integrity: "sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u", 
          crossorigin: "anonymous"}, 
          {rel: "stylesheet", 
            href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css",  
            integrity: "sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp",  
            crossorigin: "anonymous"}, 
          {rel: "stylesheet", 
            href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css",          
           crosorigin: "anonymous"}, 
          {rel: "icon", type: "image/png", sizes: "32x32", href: "/favicon-32x32.png"}
        ],
        scripts: [
          {src: "https://code.jquery.com/jquery-3.2.1.min.js",
             integrity: "sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=", 
            crossorigin: "anonymous"}, 
          {src: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js",
             integrity: "sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa",
             crossorigin: "anonymous"}
        ],
        title: options.title,
        appMountId: options.appMountId,
        bodyHtmlSnippet: "<div id='demo'></div>"
      })
```
The "options" values are specified when this is called:
```javascfript
  parts.indexTemplate({
    title: 'Free Code Camp Exercises',
    appMountId: 'app'
  }),
``` 
Builds to webpack-dev-server and production all complete with no errors and I am able to display the app.

All parameters work just fine **_except_**, the body-snippet is not added.

What am I doing wrong?

**Comment by jaketrent** [comment]
Not sure what might be wrong offhand.  @holyfirexx, does anything stick out to you?

**Comment by holyfirexx** [comment]
Sorry, didn't see this notification until today! I ran a quick test, and I can't reproduce your issue. Could you upload your generated html file? 

Update: 
Actually, I even copied your exact code above and it worked perfectly. Definitely would help to see what your generated file looks like.

**Comment by JESii** [comment]
<!DOCTYPE html>
<html lang="en" >
  <head>
    <meta charset="utf-8">
    <meta content="ie=edge" http-equiv="x-ua-compatible">

    

    
      
    

    <title>Free Code Camp Exercises</title>

    

    

    
    
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    
    
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crosorigin="anonymous">
    
    
  	<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    

    

  </head>
  <body>
    

    
    <div id="app"></div>
    
    

    

    

    
    
  	<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    
    
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    

    
    
    <script src="manifest.b34b54b3414445741a2b.js" type="text/javascript"></script>
    
    
    
    <script src="vendor.a5f2589a978b227a5ac8.js" type="text/javascript"></script>
    
    
    
    <script src="app.7b86ee96fc276e2f46ff.js" type="text/javascript"></script>
    
    
    
    <script src="style.6817b9cb9ee453fd12ca.js" type="text/javascript"></script>
    
    

    

    
  </body>
</html>

**Comment by JESii** [comment]
[https://gist.github.com/JESii/b48aef8493dc73b70bdccee08b750d40](https://gist.github.com/JESii/b48aef8493dc73b70bdccee08b750d40)

Thanks!

**Comment by holyfirexx** [comment]
Hmm. I honestly have no idea what could be going wrong. My only guess is that it has something to do with the way you are adding title and appMountId. Try hard coding those and see if it helps. When I copied your code I replaced those with random strings. That was the only difference and it all worked. 

One more thought:
The html snippets are a fairly new addition, could you be on an older version that doesn't have them?

**Comment by jaketrent** [comment]
@holyfirexx thanks for taking a look.  if it worked for you, I'm going to assume something else is going on in the environment for now.  I'll close for now. If you find more evidence that the problem is in the template, feel free to reopen this.

**Comment by JESii** [comment]
Probably the later version; I'm on the 5.6 version.

Thanks much!

**Comment by holyfirexx** [comment]
Definitely the version. html snippets weren't added until 6.1.
