### ISSUE TITLE
Rename index.html to index.ejs

### ISSUE THREAD

**Issue by jantimon** [jaketrent/html-webpack-template#7]
Hey,

could you please rename the index.html in something else e.g. index.ejs.
Otherwise the html-loader might kick in and take over the parsing which would result in not executing the lodash template code.

Also the `inject` option is set to true by default now - so you might also add `inject: false` to the example in your readme.

Thanks
Jan

**Comment by jaketrent** [comment]
Thanks for the notice on the `inject` option default change.  

Re the html-loader...  You can control what html you load with the loader options available.  Should that be enough to avoid that?  

I'm not against a rename to index.ejs.

**Comment by jantimon** [comment]
That's correct you can exclude the template or the node_modules folder but this makes it harder doesn't it?

**Comment by jaketrent** [comment]
Yes, in this case.  I wonder if this is a majority case.  I personally don't load this template via webpack loaders.  Thinking...

**Comment by jantimon** [comment]
The new plugin uses the webpack to compile the template and webpack picks up the loaders if found.
So if you add 

```
module: {
    loaders: [
      { test: /\.html$/, loader: 'html' }
    ]
  },
```

The html loader will overwrite the fallback lodash loader and the ejs commands in your template won't be executed.

**Comment by jaketrent** [comment]
I released html-webpack-template@4.0.0 that has the rename to `index.ejs`.  

This should help avoid running it through the wrong loader and hopefully be descriptive of what kind of template the file is.

@jantimon Thanks for the suggestion and the conversation.

**Comment by jantimon** [comment]
Thanks for the fast response :) :+1:

**Comment by bebraw** [comment]
Safe to close I think. :+1:
