### ISSUE TITLE
The html contains some ES6 Template String will throw errors.

### ISSUE THREAD

**Issue by lichenhao** [jaketrent/html-webpack-template#71]
RT,
When the template html contains some scripts and it contains some Template String like `some prefix ${varFoo} some suffix` will throw error `varFoo not defined.`

**Comment by glebfeklistov** [comment]
> RT,
> When the template html contains some scripts and it contains some Template String like `some prefix ${varFoo} some suffix` will throw error `varFoo not defined.`

This this module https://github.com/glebfeklistov/webpack-html-template, may be solved you problem.

**Comment by lichenhao** [comment]
thx ~~
