### ISSUE TITLE
Output location change

### ISSUE THREAD

**Issue by quantuminformation** [jaketrent/html-webpack-template#74]
I have the following output template 
```html
<script>
// my custom code from the template that needs to be loaded after webpack
</stript>

<script>
//from webpack
</stript>
```
is there a way to change the ordering so that  the webpack build isn't always at the end

**Comment by quantuminformation** [comment]
Any updates, feedback?

**Comment by GlebFeklistov** [comment]
> Any updates, feedback?

https://github.com/GlebFeklistov/webpack-html-generator, please try this. Its solved this? problem

**Comment by glebfeklistov** [comment]
> I have the following output template
> 
> ```
> <script>
> // my custom code from the template that needs to be loaded after webpack
> </stript>
> 
> <script>
> //from webpack
> </stript>
> ```
> 
> is there a way to change the ordering so that the webpack build isn't always at the end

Try this module https://github.com/glebfeklistov/webpack-html-template, his solved you problem, look jsChunks.

**Comment by quantuminformation** [comment]
thx
