### ISSUE TITLE
Add tests that verify the generated HTML

### ISSUE THREAD

**Issue by edmorley** [jaketrent/html-webpack-template#79]
Hi!

In order to make #61 (and any other changes) easier to review (since one can also review the changed expected test output) and reduce the chance of regressions, it would be great to have some tests (currently there are none) :-)

**Comment by glebfeklistov** [comment]
> Hi!
> 
> In order to make #61 (and any other changes) easier to review (since one can also review the changed expected test output) and reduce the chance of regressions, it would be great to have some tests (currently there are none) :-)

Look this solution https://github.com/glebfeklistov/webpack-html-template, may be solved you problem.
