### ISSUE TITLE
JS files are added twice

### ISSUE THREAD

**Issue by henrikbjorn** [jaketrent/html-webpack-template#8]

**Comment by jaketrent** [comment]
Please provide more details to accelerate a fix.

**Comment by jaketrent** [comment]
Others are reporting (#5) that this is because the `inject` is now defaulting to `true`.  Is that the reason for your trouble with this, or something else?

**Comment by jaketrent** [comment]
Assuming we're good now.  Closing.  Reopen if this reoccurs.

**Comment by Kikobeats** [comment]
I'm currently having the same issue: my build is injected twice times. That was the output:

``` html
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="ie6" > <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="ie7" > <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="ie8" > <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="ie9" > <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="" > <!--<![endif]-->
<head>
  <meta charset="utf-8">


  <title>Webpack App</title>





  <link href="assets/css/bundle.css?2ca814fb3609f473e60b" rel="stylesheet">




<link href="assets/css/bundle.css?2ca814fb3609f473e60b" rel="stylesheet"></head>
<body>



<div id="app"></div>









<script src="assets/js/vendor.bundle.js?2ca814fb3609f473e60b"></script>

<script src="assets/js/bundle.js?2ca814fb3609f473e60b"></script>





<script type="text/javascript" src="assets/js/vendor.bundle.js?2ca814fb3609f473e60b"></script><script type="text/javascript" src="assets/js/bundle.js?2ca814fb3609f473e60b"></script></body>
</html>
```

If I don't pass `template: require('html-webpack-template') all works fine, so something happens in the template code.

Also I try to explicit say what files link, but doesn't work:

```
files: {
  'css': [ 'main.css' ],
  'js': [ 'assets/head_bundle.js', 'assets/main_bundle.js']
}
```

another one: the HTML looks with some break lines, maybe we can avoid that from template.

**Comment by jaketrent** [comment]
@Kikobeats If you don't pass a `template` attribute, it just means that you're using the default template.  When you use this template, you should make sure that you're also passing `inject: false` so that his template can handle the injection by itself.  This tidbit is in the readme, but it wasn't in the example webpack.config.js, so I'm adding it there.  Hope that helps.

**Comment by Kikobeats** [comment]
@jaketrent thanks for the help! 😄
